instanceName: null
defaultEnable: true
namespaceSelector:
  matchNames:
    - downloads
    - media
title: null
name: "You"
theme: null
lightTheme: gazette
darkTheme: blackboard
showGreeting: true
showAppGroups: false
showAppInfo: true
showBookmarkGroups: true
customApps:
  - group: Media
    apps:
      - name: Test
        url: 'https://example.com'
        icon: test-tube
        info: This is a test app
      - name: Test2
        url: 'https://example.net'
        icon: test-tube
globalBookmarks:
  - group: Communicate
    links:
      - name: Discord
        url: 'https://discord.com'
      - name: Gmail
        url: 'http://gmail.com'
      - name: Slack
        url: 'https://slack.com/signin'
  - group: Cloud
    links:
      - name: Box
        url: 'https://box.com'
      - name: Dropbox
        url: 'https://dropbox.com'
      - name: Drive
        url: 'https://drive.google.com'
  - group: Design
    links:
      - name: Awwwards
        url: 'https://awwwards.com'
      - name: Dribbble
        url: 'https://dribbble.com'
      - name: Muz.li
        url: 'https://medium.muz.li/'
  - group: Dev
    links:
      - name: Codepen
        url: 'https://codepen.io/'
      - name: Devdocs
        url: 'https://devdocs.io'
      - name: Devhints
        url: 'https://devhints.io'
  - group: Lifestyle
    links:
      - name: Design Milk
        url: 'https://design-milk.com/category/interior-design/'
      - name: Dwell
        url: 'https://www.dwell.com/'
      - name: Freshome
        url: 'https://www.mymove.com/freshome/'
  - group: Media
    links:
      - name: Spotify
        url: 'http://browse.spotify.com'
      - name: Trakt
        url: 'http://trakt.tv'
      - name: YouTube
        url: 'https://youtube.com/feed/subscriptions'
  - group: Reading
    links:
      - name: Instapaper
        url: 'https://www.instapaper.com/u'
      - name: Medium
        url: 'http://medium.com'
      - name: Reddit
        url: 'http://reddit.com'
  - group: Tech
    links:
      - name: TheNextWeb
        url: 'https://thenextweb.com/'
      - name: The Verge
        url: 'https://theverge.com/'
      - name: MIT Technology Review
        url: 'https://www.technologyreview.com/'
